version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
#   depends_on:
#       - wordpress
    ports:
        - "80:80"

#       Lembrar de adicionar o volume wordpress que será criado

#   reiniciará os containers sempre que ocorrer qualquer falha
    restart: always